# Generated by Django 6.0.4 on 2026-04-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("national", "National"),
                            ("state", "State"),
                            ("district", "District"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("round", models.PositiveSmallIntegerField(default=1)),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "unique_together": {("year", "round")},
            },
        ),
    ]
