# Generated by Django 6.0.4 on 2026-04-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="tse_election_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
