# Generated by Django 6.0.4 on 2026-04-09 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("abbreviation", models.CharField(max_length=20, unique=True)),
                ("number", models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                "verbose_name_plural": "Parties",
            },
        ),
        migrations.CreateModel(
            name="PoliticalPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("cpf", models.CharField(max_length=11, unique=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=20)),
                ("race", models.CharField(blank=True, max_length=40)),
                ("education_level", models.CharField(blank=True, max_length=60)),
                ("occupation", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name_plural": "Political people",
            },
        ),
        migrations.CreateModel(
            name="Coalition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coalitions",
                        to="elections.election",
                    ),
                ),
                (
                    "parties",
                    models.ManyToManyField(
                        related_name="coalitions", to="entities.party"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartyMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="entities.party",
                    ),
                ),
                (
                    "political_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_memberships",
                        to="entities.politicalperson",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Candidacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ballot_name", models.CharField(max_length=200)),
                ("number", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=40)),
                ("state", models.CharField(max_length=2)),
                ("photo_url", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidacies",
                        to="elections.election",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidacies",
                        to="elections.position",
                    ),
                ),
                (
                    "coalition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidacies",
                        to="entities.coalition",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidacies",
                        to="entities.party",
                    ),
                ),
                (
                    "political_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidacies",
                        to="entities.politicalperson",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Candidacies",
            },
        ),
    ]
