# Generated by Django 6.0.4 on 2026-04-17 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("elections", "0002_election_tse_election_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Legislature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("abbreviation", models.CharField(max_length=20, unique=True)),
                ("number", models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                "verbose_name_plural": "Parties",
            },
        ),
        migrations.CreateModel(
            name="PoliticalPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=11, null=True, unique=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=20)),
                ("race", models.CharField(blank=True, max_length=40)),
                ("education_level", models.CharField(blank=True, max_length=60)),
                ("occupation", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name_plural": "Political people",
            },
        ),
        migrations.CreateModel(
            name="Proposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camara_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("bill_type", models.CharField(max_length=20)),
                ("number", models.PositiveIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                ("summary", models.TextField(blank=True)),
                ("keywords", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Coalition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coalitions",
                        to="elections.election",
                    ),
                ),
                (
                    "parties",
                    models.ManyToManyField(
                        related_name="coalitions", to="entities.party"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartyMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="entities.party",
                    ),
                ),
                (
                    "political_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_memberships",
                        to="entities.politicalperson",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Candidacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ballot_name", models.CharField(max_length=200)),
                ("number", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=40)),
                ("state", models.CharField(max_length=2)),
                ("photo_url", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "tse_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidacies",
                        to="elections.election",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidacies",
                        to="elections.position",
                    ),
                ),
                (
                    "coalition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidacies",
                        to="entities.coalition",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidacies",
                        to="entities.party",
                    ),
                ),
                (
                    "political_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidacies",
                        to="entities.politicalperson",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Candidacies",
            },
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_text", models.TextField(blank=True)),
                ("pdf_url", models.URLField(blank=True)),
                (
                    "candidacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="entities.candidacy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("education", "Educação"),
                            ("health", "Saúde"),
                            ("security", "Segurança"),
                            ("economy", "Economia"),
                            ("environment", "Meio Ambiente"),
                            ("infrastructure", "Infraestrutura"),
                            ("social", "Social"),
                            ("children", "Crianças e Adolescentes"),
                            ("other", "Outros"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("extracted_by", models.CharField(blank=True, max_length=20)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promises",
                        to="entities.proposal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VotingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "camara_id",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                ("date", models.DateTimeField()),
                ("description", models.TextField(blank=True)),
                ("approved", models.BooleanField(null=True)),
                ("body", models.CharField(max_length=20)),
                (
                    "proposition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voting_sessions",
                        to="entities.proposition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[
                            ("sim", "Sim"),
                            ("nao", "Não"),
                            ("abstencao", "Abstenção"),
                            ("obstrucao", "Obstrução"),
                            ("artigo17", "Art. 17"),
                        ],
                        max_length=20,
                    ),
                ),
                ("camara_deputy_id", models.PositiveIntegerField(db_index=True)),
                ("date", models.DateTimeField()),
                (
                    "political_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="entities.politicalperson",
                    ),
                ),
                (
                    "voting_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="entities.votingsession",
                    ),
                ),
            ],
            options={
                "unique_together": {("voting_session", "camara_deputy_id")},
            },
        ),
    ]
