# Generated by Django 6.0.4 on 2026-04-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidacy",
            name="tse_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="politicalperson",
            name="cpf",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
