# Generated by Django 6.0.4 on 2026-04-09 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0002_candidacy_tse_id_alter_politicalperson_cpf"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_text", models.TextField(blank=True)),
                ("pdf_url", models.URLField(blank=True)),
                (
                    "candidacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="entities.candidacy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("education", "Educação"),
                            ("health", "Saúde"),
                            ("security", "Segurança"),
                            ("economy", "Economia"),
                            ("environment", "Meio Ambiente"),
                            ("infrastructure", "Infraestrutura"),
                            ("social", "Social"),
                            ("children", "Crianças e Adolescentes"),
                            ("other", "Outros"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("extracted_by", models.CharField(blank=True, max_length=20)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promises",
                        to="entities.proposal",
                    ),
                ),
            ],
        ),
    ]
