# Generated by Django 6.0.4 on 2026-04-09 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entities", "0003_proposal_promise"),
    ]

    operations = [
        migrations.CreateModel(
            name="Legislature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(unique=True)),
                ("start_year", models.PositiveSmallIntegerField()),
                ("end_year", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Proposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camara_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("bill_type", models.CharField(max_length=20)),
                ("number", models.PositiveIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                ("summary", models.TextField(blank=True)),
                ("keywords", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="VotingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "camara_id",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                ("date", models.DateTimeField()),
                ("description", models.TextField(blank=True)),
                ("approved", models.BooleanField(null=True)),
                ("body", models.CharField(max_length=20)),
                (
                    "proposition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voting_sessions",
                        to="legislature.proposition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[
                            ("sim", "Sim"),
                            ("nao", "Não"),
                            ("abstencao", "Abstenção"),
                            ("obstrucao", "Obstrução"),
                            ("artigo17", "Art. 17"),
                        ],
                        max_length=20,
                    ),
                ),
                ("camara_deputy_id", models.PositiveIntegerField(db_index=True)),
                ("date", models.DateTimeField()),
                (
                    "political_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="entities.politicalperson",
                    ),
                ),
                (
                    "voting_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="legislature.votingsession",
                    ),
                ),
            ],
            options={
                "unique_together": {("voting_session", "camara_deputy_id")},
            },
        ),
    ]
